POST http://localhost:3001/register/
Content-Type: application/json

{
    "username": "raj",
    "name": "raj",
    "password": "1234"
}

###

POST http://localhost:3001/admin/register/
Content-Type: application/json

{
    "username": "admin",
    "name": "administrator",
    "password": "admin1234"
}

###
POST http://localhost:3001/login/
Content-Type: application/json

{
    "username": "raj",
    "password": "1234"
}

###

# eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJyYWoiLCJuYW1lIjoicmFqIiwiUEFTU1dPUkQiOiIkMmIkMTAkMXV5M3JxQnJsWnd2VWNDOUFrTDAvZUhydEhiWkRzZXEudzFjWHgyWEFBRGhOSC56cUExUE8iLCJpYXQiOjE3MTE5MDE2Nzd9.i6CPwHhZ0lNsVqgr9Lxb4FqbFF3bQ6dbCcUzrh0eOb4

###

POST http://localhost:3001/admin/login/
Content-Type: application/json

{
    "username": "admin",
    "password": "admin1234"
}

###

GET http://localhost:3001/products
#Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJyYWoiLCJuYW1lIjoicmFqIiwicGFzc3dvcmQiOiIkMmIkMTAkQjdMUkliOW9pQjREa00ueU0xOGJxLjRObnU2L3d5ak5mLlFyWEhtREdqRUdTb1BlNUUySEciLCJpYXQiOjE3MTE5ODA2Njl9.T-v1nF-HBuSFWWBSIr_ncstwZsOm-9qQs5s1YLY6lvw
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbiIsIm5hbWUiOiJhZG1pbmlzdHJhdG9yIiwicGFzc3dvcmQiOiIkMmIkMTAkd1FwNWhTSnhXeFFKcVRxdVBVczR6LnhYUUxjZWEvZ0xKZ0FURGg0U3oyTkhscW9sRXhpSFciLCJpc19hZG1pbiI6MSwiaWF0IjoxNzEyMDczNTEzfQ.lxj3O4_rvEQSU7I8qPg51rlQCvWso7_UtJlFa-V0Ngo
###

GET http://localhost:3001/products?orderBy=price&order=DESC
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJyYWoiLCJuYW1lIjoicmFqIiwicGFzc3dvcmQiOiIkMmIkMTAkQjdMUkliOW9pQjREa00ueU0xOGJxLjRObnU2L3d5ak5mLlFyWEhtREdqRUdTb1BlNUUySEciLCJpYXQiOjE3MTE5ODA2Njl9.T-v1nF-HBuSFWWBSIr_ncstwZsOm-9qQs5s1YLY6lvw

###

GET http://localhost:3001/products/12/
#Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJyYWoiLCJuYW1lIjoicmFqIiwicGFzc3dvcmQiOiIkMmIkMTAkQjdMUkliOW9pQjREa00ueU0xOGJxLjRObnU2L3d5ak5mLlFyWEhtREdqRUdTb1BlNUUySEciLCJpYXQiOjE3MTE5ODA2Njl9.T-v1nF-HBuSFWWBSIr_ncstwZsOm-9qQs5s1YLY6lvw
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbiIsIm5hbWUiOiJhZG1pbmlzdHJhdG9yIiwicGFzc3dvcmQiOiIkMmIkMTAkd1FwNWhTSnhXeFFKcVRxdVBVczR6LnhYUUxjZWEvZ0xKZ0FURGg0U3oyTkhscW9sRXhpSFciLCJpc19hZG1pbiI6MSwiaWF0IjoxNzEyMDczNTEzfQ.lxj3O4_rvEQSU7I8qPg51rlQCvWso7_UtJlFa-V0Ngo

###

POST http://localhost:3001/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJyYWoiLCJuYW1lIjoicmFqIiwicGFzc3dvcmQiOiIkMmIkMTAkQjdMUkliOW9pQjREa00ueU0xOGJxLjRObnU2L3d5ak5mLlFyWEhtREdqRUdTb1BlNUUySEciLCJpYXQiOjE3MTE5ODA2Njl9.T-v1nF-HBuSFWWBSIr_ncstwZsOm-9qQs5s1YLY6lvw
Content-Type: application/json

{
    "productName": "Clips",
    "imageUrl": "https://5.imimg.com/data5/PK/QK/GY/SELLER-81178992/snap-hair-clips-500x500.jpg",
    "price": 10
}

###

PUT http://localhost:3001/products/11/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJyYWoiLCJuYW1lIjoicmFqIiwicGFzc3dvcmQiOiIkMmIkMTAkQjdMUkliOW9pQjREa00ueU0xOGJxLjRObnU2L3d5ak5mLlFyWEhtREdqRUdTb1BlNUUySEciLCJpYXQiOjE3MTE5ODA2Njl9.T-v1nF-HBuSFWWBSIr_ncstwZsOm-9qQs5s1YLY6lvw
Content-Type: application/json

{
    "productName": "Hair Clip"
}

# {
#     "price": 30
# }

###

DELETE http://localhost:3001/products/10/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbiIsIm5hbWUiOiJhZG1pbmlzdHJhdG9yIiwicGFzc3dvcmQiOiIkMmIkMTAkd1FwNWhTSnhXeFFKcVRxdVBVczR6LnhYUUxjZWEvZ0xKZ0FURGg0U3oyTkhscW9sRXhpSFciLCJpc19hZG1pbiI6MSwiaWF0IjoxNzEyMDczNTEzfQ.lxj3O4_rvEQSU7I8qPg51rlQCvWso7_UtJlFa-V0Ngo

###

GET http://localhost:3001/users/

###

GET http://localhost:3001/admins/ 

###

GET http://localhost:3001/user-profile/
#Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbiIsIm5hbWUiOiJhZG1pbmlzdHJhdG9yIiwicGFzc3dvcmQiOiIkMmIkMTAkd1FwNWhTSnhXeFFKcVRxdVBVczR6LnhYUUxjZWEvZ0xKZ0FURGg0U3oyTkhscW9sRXhpSFciLCJpc19hZG1pbiI6MSwiaWF0IjoxNzEyMDczNTEzfQ.lxj3O4_rvEQSU7I8qPg51rlQCvWso7_UtJlFa-V0Ngo
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJyYWoiLCJuYW1lIjoicmFqIiwicGFzc3dvcmQiOiIkMmIkMTAkQjdMUkliOW9pQjREa00ueU0xOGJxLjRObnU2L3d5ak5mLlFyWEhtREdqRUdTb1BlNUUySEciLCJpYXQiOjE3MTE5ODA2Njl9.T-v1nF-HBuSFWWBSIr_ncstwZsOm-9qQs5s1YLY6lvw

###

GET http://localhost:3001/cart/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJyYWoiLCJuYW1lIjoicmFqIiwicGFzc3dvcmQiOiIkMmIkMTAkQjdMUkliOW9pQjREa00ueU0xOGJxLjRObnU2L3d5ak5mLlFyWEhtREdqRUdTb1BlNUUySEciLCJpYXQiOjE3MTE5ODA2Njl9.T-v1nF-HBuSFWWBSIr_ncstwZsOm-9qQs5s1YLY6lvw
#Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbiIsIm5hbWUiOiJhZG1pbmlzdHJhdG9yIiwicGFzc3dvcmQiOiIkMmIkMTAkd1FwNWhTSnhXeFFKcVRxdVBVczR6LnhYUUxjZWEvZ0xKZ0FURGg0U3oyTkhscW9sRXhpSFciLCJpc19hZG1pbiI6MSwiaWF0IjoxNzEyMDczNTEzfQ.lxj3O4_rvEQSU7I8qPg51rlQCvWso7_UtJlFa-V0Ngo

###

POST http://localhost:3001/cart/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJyYWoiLCJuYW1lIjoicmFqIiwicGFzc3dvcmQiOiIkMmIkMTAkQjdMUkliOW9pQjREa00ueU0xOGJxLjRObnU2L3d5ak5mLlFyWEhtREdqRUdTb1BlNUUySEciLCJpYXQiOjE3MTE5ODA2Njl9.T-v1nF-HBuSFWWBSIr_ncstwZsOm-9qQs5s1YLY6lvw
Content-Type: application/json

# {
#     "productId": 1,
#     "productName": "shirt",
#     "quantity": 10
# }

{
    "productId": 2,
    "productName": "pant",
    "quantity": 1
}

###

DELETE http://localhost:3001/cart/2/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJyYWoiLCJuYW1lIjoicmFqIiwicGFzc3dvcmQiOiIkMmIkMTAkQjdMUkliOW9pQjREa00ueU0xOGJxLjRObnU2L3d5ak5mLlFyWEhtREdqRUdTb1BlNUUySEciLCJpYXQiOjE3MTE5ODA2Njl9.T-v1nF-HBuSFWWBSIr_ncstwZsOm-9qQs5s1YLY6lvw
 